###  DOCKER COMPOSE ###
version: "3"

networks:
  fastapi-pytho38-mongo:

services:
  # app container
  app:
    build: .
    image: jotunheim
    container_name: jotunheim
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    restart: always
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - fastapi-pytho38-mongo

  # mongodb container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
      # - MONGO_INITDB_ROOT_DATABASE=root-db
      - MONGO_INITDB_DATABASE=root-db
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - fastapi-pytho38-mongo

volumes:
  dbdata:
